# -*- coding: utf-8 -*-
"""Cópia de Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uwGOJHEUeJYGV1JloyRZ-mEQHE0XgjAC

# Análise Base Ataque Cardíaco

## Breve Explicação da Base

Essa base de dados parece ser um conjunto de dados relacionados a pacientes com problemas cardíacos, com várias variáveis ​​de entrada (ou recursos) e uma variável de saída (ou rótulo) indicando se o paciente possui ou não uma doença cardíaca. As colunas na base de dados representam as seguintes informações:

age: idade do paciente em anos (variável numérica)
sex: gênero do paciente (1 para masculino, 0 para feminino) (variável categórica)
cp: tipo de dor no peito relatada pelo paciente (variável categórica)
trtbps: pressão arterial em repouso (em mm Hg) (variável numérica)
chol: nível de colesterol sérico (em mg/dL) (variável numérica)
fbs: nível de açúcar no sangue em jejum (> 120 mg/dL representa verdadeiro, 0 representa falso) (variável categórica)
restecg: resultado do eletrocardiograma em repouso (variável categórica)
thalachh: frequência cardíaca máxima alcançada (variável numérica)
exng: angina induzida por exercício (1 representa verdadeiro, 0 representa falso) (variável categórica)
oldpeak: depressão do segmento ST induzida por exercício em relação ao repouso (variável numérica)
slp: inclinação do segmento ST de pico do exercício (variável categórica)
caa: número de vasos principais coloridos por fluoroscopia (variável numérica)
thall: resultado do teste de estresse com tálio (variável categórica)
output: presença de doença cardíaca (1 representa verdadeiro, 0 representa falso) (variável categórica)

## Breve Explicação dos Dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/heart.csv')
df.head()

tipos = df.dtypes
tipos

resumo_estatistico = df.describe()
resumo_estatistico

"""## Análise Univariada (uma variável)"""

# Separar variáveis numéricas manualmente
vars_numericas = ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'caa']

# Plotar histograma para as variáveis numéricas
for var in vars_numericas:
    plt.hist(df[var], bins=10)
    plt.title('Histograma de ' + var)
    plt.xlabel(var)
    plt.ylabel('Frequência')
    plt.show()

# Variáveis categóricas
variaveis_categoricas = ['sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall', 'output']

# Plotar gráficos de frequência para as variáveis categóricas
for var in variaveis_categoricas:
    plt.figure(figsize=(8, 6))
    df[var].value_counts().sort_index().plot(kind='bar', rot=0)
    plt.title(f'Frequência de Valores para {var}')
    plt.xlabel(var)
    plt.ylabel('Frequência')
    plt.show()

"""## Análise Bivariada (duas ou mais variáveis)"""

# Variáveis numéricas
variaveis_numericas = ['age', 'trtbps', 'chol', 'thalachh', 'oldpeak', 'caa']

# Plotar gráfico de frequência para cada variável numérica, considerando o output como divisor
for var in variaveis_numericas:
    plt.figure(figsize=(8, 6))
    df[df['output'] == 0][var].plot(kind='hist', alpha=0.5, label='output = 0')
    df[df['output'] == 1][var].plot(kind='hist', alpha=0.5, label='output = 1')
    plt.xlabel(var)
    plt.ylabel('Frequência')
    plt.title(f'Gráfico de Frequência para {var}')
    plt.legend()
    plt.show()

# Lista das variáveis categóricas
variaveis_categoricas = ['sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall', 'output']

# Plotar gráfico de frequência para as variáveis categóricas
for coluna in variaveis_categoricas:
    plt.figure(figsize=(8, 6))
    df[df['output'] == 0][coluna].value_counts().sort_index().plot(kind='bar', color='blue', alpha=0.7, label='0')
    df[df['output'] == 1][coluna].value_counts().sort_index().plot(kind='bar', color='red', alpha=0.7, label='1')
    plt.title(f'Frequência de {coluna} por Output')
    plt.xlabel(coluna)
    plt.ylabel('Frequência')
    plt.legend(title='Output', loc='upper right')
    plt.show()

# Variáveis categóricas
categorical_vars = ['age', 'sex', 'cp', 'fbs', 'restecg', 'exng', 'slp', 'caa', 'thall']

# Plotar gráficos de frequência para as variáveis categóricas
for var in categorical_vars:
    plt.figure(figsize=(8, 6))
    df.groupby([var, 'output']).size().unstack().plot(kind='bar', stacked=False)
    plt.title(f'Frequência de {var} por output')
    plt.xlabel(var)
    plt.ylabel('Frequência')
    plt.legend(['No Disease', 'Disease'])
    plt.show()

# Cria o heatmap de correlação
corr = df.corr() # Substitua "df" pelo nome do seu dataframe
plt.figure(figsize=(10, 8)) # Define o tamanho da figura
sns.heatmap(corr, annot=True, cmap='coolwarm') # Configura o heatmap
plt.title('Heatmap de Correlação') # Define o título do gráfico
plt.show() # Exibe o gráfico

"""## Perguntas a serem feitas e respostas

Qual é a distribuição de idade dos pacientes que sofreram ataque cardíaco?

Existe alguma diferença na distribuição de idade entre pacientes do sexo masculino e feminino que sofreram ataque cardíaco?

Quais são os fatores de risco mais comuns para ataques cardíacos, com base nas variáveis disponíveis?

Existe uma correlação entre a pressão arterial sistólica (trtbps) e o colesterol (chol) dos pacientes?

Como a frequência cardíaca máxima alcançada (thalachh) está relacionada com a presença de dor no peito (cp)?

É possível identificar um padrão de comportamento de exercício induzido por angina (exng) em relação à presença de doença cardíaca (output)?

Como os níveis de depressão do segmento ST induzida pelo exercício (oldpeak) estão relacionados com a presença de doença cardíaca?

Qual é a distribuição da presença de doença cardíaca (output) em relação aos diferentes tipos de dor no peito (cp)?

Existe alguma diferença na distribuição da presença de doença cardíaca em pacientes com e sem histórico de açúcar elevado no sangue (fbs)?

Como as variáveis categóricas, como sexo, número de vasos principais coloridos (caa), e tipo de deficiência thalassemia (thall), estão relacionadas com a presença de doença cardíaca?

### Qual é a distribuição de idade dos pacientes que sofreram ataque cardíaco?

Gráfico tal demonstra que mulheres tem uma média de idade menor do que os homens nessa amostra
"""

